# Generated by Django 5.2.12 on 2026-05-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='pending_data',
            field=models.TextField(blank=True, help_text='JSON blob of {name, password, role} so verify-email works cross-device', null=True),
        ),
    ]
