# Generated by Django 6.0.4 on 2026-05-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_pending_data_to_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
